"""d migrate1

Revision ID: 65b10e242f3b
Revises: f11325aecf8e
Create Date: 2019-04-25 17:47:01.047431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b10e242f3b'
down_revision = 'f11325aecf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_statement', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_statement')
    # ### end Alembic commands ###
